import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ColorModeContext, useMode } from "../theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import Topbar from "../components/Topbar";
import Sidebar from "../components/Sidebar";
import "@fullcalendar/common/main.css";
import "@fullcalendar/daygrid/main.css";
import "@fullcalendar/timegrid/main.css";

export default function App({ Component, pageProps }: AppProps) {
	const [theme, colorMode] = useMode();
	return (
		<ColorModeContext.Provider value={colorMode}>
			<ThemeProvider theme={theme}>
				<CssBaseline />
				<div className="app">
					<Head>
						<title>Create Next App</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<Sidebar />
					<main className="content">
						<Topbar />
						<Component {...pageProps} />
					</main>
				</div>
			</ThemeProvider>
		</ColorModeContext.Provider>
	);
}
